num="23456"
num_int=int(num)
print("The number after type casting is : ",num_int)
print("The type of the number after type casting is : ",type(num_int))
num_float=float(num)
print("The number after type casting is : ",num_float)
print("The type of the number after type casting is : ",type(num_float))
num_str=str(num)
print("The number after type casting is : ",num_str)
print("The type of the number after type casting is : ",type(num_str))
num_complex=complex(num)
print("The number after type casting is : ",num_complex)
print("The type of the number after type casting is : ",type(num_complex))
num_bool=bool(num)
print("The number after type casting is : ",num_bool)
print("The type of the number after type casting is : ",type(num_bool))
